config/routes.rb
Rails.application.routes.draw do
  resources :genres
  root 'movies#index'
  get 'movies/filter/:filter', to: 'movies#index', as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favorites, only: %i[create destroy]
  end

  resource :session, only: %i[new create destroy]

  resources :users
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
    
<footer>
  <p>Copyright &copy; 
    <%= Time.now.year %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class= "row space-beetwen">
  <nav>
    <div class="logo">
      <%= link_to image_tag('logo.png'), root_path, alt:"logo" %>
    </div>
    <ul class="left">
      <li><%= nav_link_to "Released", movies_path %></li>
      <li><%= nav_link_to "Recent", filtered_movies_path(:recent) %></li>
      <li><%= nav_link_to "Hits", filtered_movies_path(:hits) %></li>
      <li><%= nav_link_to "Flops", filtered_movies_path(:flops) %></li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li><%= link_to current_user.name, current_user %></li>
        <li><%= link_to "Account Settings", edit_user_path(current_user)%></li>
        <li><%= link_to "Sign Out", session_path, method: :delete, class: "Button"%></li>
      <% else %>
        <li><%= link_to "Sign Up", signup_path, class: "button" %></li>
        <li><%= link_to "Sign In", signin_path, class: "button" %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix-App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>